add changes for new filename and strcuture

diff --git a/jobs/JAIGEFS_TC_TRACK b/jobs/JAIGEFS_TC_TRACK
--- a/jobs/JAIGEFS_TC_TRACK
+++ b/jobs/JAIGEFS_TC_TRACK
@@ -6,7 +6,6 @@ set -x
 ####################################
 # obtain unique process id (pid) and make temp directory
 ####################################
-#export jobid=${jobid:-$job.o$$}
 export DATA=${DATA:-${DATAROOT:?}/${jobid}}
 mkdir -p $DATA
 cd $DATA
@@ -17,11 +16,12 @@ export cycle=t${cyc}z
 ####################################
 #export jlogfile=${jlogfile:-${DATA}/jlogfile.${jobid}}
 
+export ECMWF_FILE_EXT=${ECMWF_FILE_EXT:-1}
 ####################################
 # Specify NET and RUN Name and model
 ####################################
 export NET=${NET:-ens_tracker}
-export RUN=${RUN:-mgfs}
+export RUN=${RUN:-aigefs}
 
 ####################################
 # Determine Job Output Name on System
@@ -46,7 +46,6 @@ export EXECens_tracker=${EXECens_tracker:-$HOMEens_tracker/exec}
 export FIXens_tracker=${FIXens_tracker:-$HOMEens_tracker/fix}
 export USHens_tracker=${USHens_tracker:-$HOMEens_tracker/ush}
 
-##############################
 # Run setpdy and initialize PDY variables
 ##############################
 setpdy.sh
@@ -54,8 +53,10 @@ setpdy.sh
 ##############################################
 # Define COM directories
 ##############################################
-export COMINmlgfs=${COMINmlgfs:-$(compath.py $envir/com/gfs/${gfs_ver})/mlgfs.${PDY}}
+export JYYYY=`echo ${PDY} | cut -c1-4`
+export COMINgfs=${COMINgfs:-$(compath.py $envir/com/gfs/${gfs_ver})/gfs.${PDY}}
 export COMINsyn=${COMINsyn:-$(compath.py $envir/com/gfs/${gfs_ver})/syndat}
+export COMINaigefs=${COMINaigefs:-$(compath.py $envir/com/aigefs/${aigefs_ver})/aigefs.${PDY}/${cyc}}/model
 
 export COMOUT=${COMOUT:-$(compath.py -o ${NET}/${ens_tracker_ver})/${RUN}.${PDY}/${cyc}/tctrack}
 export COMOUThur=${COMOUThur:-$(compath.py -o ${NET}/${ens_tracker_ver})/global}
@@ -65,38 +66,72 @@ mkdir -m 775 -p $COMOUT $COMOUThur $COMOUTatcf
 msg="HAS BEGUN on `hostname`"
 postmsg "$jlogfile" "$msg"
 
-env
+#env
 
 #############################################################
 # Execute the script
-export cmodel=mgfs
+export cmodel=aigefs
 export loopnum=1
 export ymdh=${PDY}${cyc}
 
-export mlgfsdir=${COMINmlgfs}/${cyc}
-export pert="p01"
-pertdir=${DATA}/${cmodel}/${pert}
-mkdir -p $pertdir
+export ensdira=${COMINaigefs}
+export ensdirb=${COMINaigefs}
 
-#-----------input data checking -----------------
-${USHens_tracker}/data_check_mgfs.sh 
-# exit code 6 = missing data of opportunity
-if [ $? -eq 6 ]; then exit; fi
-#------------------------------------------------
+mkdir ${DATA}/${cmodel}
+cd ${DATA}/${cmodel}
 
-${USHens_tracker}/extrkr_ml.sh ${loopnum} ${cmodel} ${ymdh} ${pert} ${pertdir} #2>&1 >${outfile}  
+export pertstring="000 001 002 003 004 005 006 007 008 009 010
+                       011 012 013 014 015 016 017 018 019 020
+                       021 022 023 024 025 026 027 028 029 030"
 
+>trkr.cmdfile
+for pert in ${pertstring}; do
+
+  pertdir=${DATA}/${cmodel}/mem${pert}
+  mkdir -p $pertdir
+  cd $pertdir
+
+  ##-----------input data checking -----------------
+  ${USHens_tracker}/data_check_aigefs.sh $pert
+  # exit code 6 = missing data of opportunity
+  if [ $? -eq 6 ]; then exit; fi
+  #------------------------------------------------
+
+  ##-----------generate hurricane track-------------
+  outfile=${pertdir}/trkr.${cmodel}.m${pert}.${ymdh}.out
+  echo "${USHens_tracker}/extrkr_ai.sh ${loopnum} ${cmodel} ${ymdh} ${pert} ${pertdir} 2>&1 >${outfile}" >>trkr.cmdfile
+
+done
+
+chmod u+x trkr.cmdfile
+export MP_PGMMODEL=mpmd
+export MP_CMDFILE=${DATA}/${cmodel}/trkr.cmdfile
+
+mpiexec --cpu-bind core --configfile ${MP_CMDFILE}
 export err=$?; err_chk
 
-if [ "$SENDCOM" = 'YES' ]; then
-  if [ -s ${pertdir}/trak.mgfs.atcfunix.${PDY}${cyc} ]; then
-    cp ${pertdir}/trak.mgfs.atcfunix.${PDY}${cyc} ${COMOUT}/mgfs.t${cyc}z.cyclone.trackatcfunix
+#if [ ${SENDCOM} = 'NO' ]; then
+#  for pert in ${pertstring}; do
+#    pertdir=${DATA}/${cmodel}/${pert}
+#    cp ${pertdir}/trak.a${pert}.atcfunix.${PDY}${cyc} ${COMOUT}/a${pert}.t${cyc}z.cyclone.trackatcfunix
+#  done
+#fi
 
-    cat ${pertdir}/trak.mgfs.atcfunix.${PDY}${cyc} | \
-      sed s:mgfs:MGFS:g \
-    > ${COMOUT}/mgfs.t${cyc}z.cyclone.trackatcfunix
-  fi
-fi
+cd $DATA
+#rm -rf ${DATA}/${cmodel}
+
+${USHens_tracker}/ens_trak_ave.sh
+export err=$?; err_chk
+
+#if [ ${SENDCOM} = 'NO' ]; then
+#  cp ${DATA}/aemn.trkprob.* ${COMOUT}/
+#  cp ${DATA}/trak.aemn.atcfunix.* ${COMOUT}/aemn.t${cyc}z.cyclone.trackatcfunix
+#  cp ${DATA}/trak.aemn.mode.* ${COMOUT}/aemn.t${cyc}z.cyclone.trackmode
+#  cp ${DATA}/trak.aemn.spread.* ${COMOUT}/aemn.t${cyc}z.cyclone.trackspread
+#fi
+
+#${USHens_tracker}/atcf_2_cxml.sh ${cmodel} ${ymdh} ${COMOUT} ${DATA}
+#export err=$?; err_chk
 
 #############################################################
 
@@ -109,5 +144,6 @@ postmsg "$jlogfile" "$msg"
 if [[ $KEEPDATA != "YES" ]]; then
   rm -rf $DATA
 fi
+
 
 date
